[package]
name = "mygraphs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.26.2"
env_logger = "0.11.3"
rand = "0.8.5"
thiserror = "1.0.57"
voronoi = "0.1.4"
